use com.vvv.ui
use acessibilidade.odele.gxu.ui
use talk.back.ui
bootscreen() {
print("BOOTING");
frames[(frame)!!#"frames"] {
1(.) 2(..) 3(...)
return loop;
}
}
AppsManager() {
'packages/'
apps_list*>='apps'
}
animation() {
322>882>88!*>2>393>33>3344>3>454>4>44>4>4>4<23
3829>2>2>233>32>4>4>33>23><29>239292>229>282>2929
fps *= ?>1>44<77>33>448>393>2929
fps *= ?>1>54<77
fps *= ?>1>82<77
fps *= ?>1>82<77
animation[
39¿·μ3<¿]¿3<μ·°<3<¿μ{°<¥<¿μ<3<°
°]°]°<°<μ°<°{μ>`¥·§°<°°₪₪¥μ{°°·μ°<°·°μ<<
cpu_!_!€÷$'÷_÷€:€=€=$==$==$==$'(€÷#_÷€:_=€÷_#
!$$!!_!_#_=_!_!&#_!!_!_#&!_!#_÷$÷_!_!$!÷$mation
eudufiK$_!_#$÷$=$#$÷$÷÷$393€#_#3NULL€÷_##$NULL
NULL€÷'_÷€!$÷€×€=€=$÷$÷€!€÷€÷€÷#$EIFIROG_!$÷€÷#€EIFK
DIKDKFKDKIXKD_÷_'*€÷_:£÷×£€€<`<`>`{<<[﷼﷼฿ΩΘฯΘΩ฿฿ΩΘฯ92929393939
_!_!÷_:_÷(×€#_!(÷!_(÷_!_!!$!_!_!_!_!_!_!_!_!_#_!_÷
_!_!$÷!$!_÷_÷$:€=€÷€#$=$÷#_#_÷$!\!\#\!&!_÷_!_!$##$!
_!_!!$!_!_!_!_!_!_!_!_!_!_!_!_'&#$÷'&÷€÷€-_÷$!$!$-$!-$#$
*$_!!_!_÷_!_÷_÷_÷_#÷_÷$#_÷÷$#_#$#_=_#_!÷_
*_!!_÷_
!\÷#
÷÷_#_÷$÷$#$÷_÷_÷!_#_!_!&!&!&!&!&!&!_#_#_!#$÷
'&=!'\÷÷÷!_
÷÷&#÷#
:÷=
=
!
!%_$!%$!%_-$%!$!%!
!/_/#(-/$!$-/$-/-/
-_;!_!;__-/_/-_/--$#$#$'-/-/-/-/-//--//-//-//-
÷\#_÷$÷$#$÷$÷$#$÷$÷$!$!$#_'_#=$"&÷$÷€#$#$
÷€#$'€÷€÷:$!$÷€#_#€#€?*_!#????·°·°<ΜΜ·§]¿¤>¿·Μ<`<°<Μ
§{Μ<¿>°{|>¥·￦<Μ°·¥<Μ]©·°·Μ·|·§°₪Μ₪©₪Μ₪Μ₪₪Μ©₪©₪©©₪|₪₹₹₪¤₹₪₹₪₹₪₹₹₪₹₪₹៛₪₹Μ៛§{Μ<¬
§·§·§·§{|₪|₪|₹₪₹₪₹₪₹ռօռօռօռօֆօգըօըռճեօճռ
եօօռռօռօեօդօռռօռօိသ်သ်သ်
ိူ်ူ်ူ််သ292်ူန92်သ်သနသနသ3သ်နစနသ်သနစနသ်န939န9392992922
ဖ့ြြြြြြြူ်သါးမါုခ်ူါုု်သ်ိူ်ု်
ိူိူိူဖူိူိူခး်ူိိူ်ုထ်ူိူိူ်ု်သနါူ်ု့ဘည်ိညိာထ.ိူထ,ိ်ိူ်ုိိုိ
ူျူိူ်သ်သ်ူ်ူ်ထူ်ူ်ူိူိူိူိူ်ူ်ူိူိူိုိုိုိိူိုိသိထုနစဖူဖ
!%_$!%$!%_-$%!$!%!
!/_/#(-/$!$-/$-/-/
-_;!_!;__-/_/-_/--$#$#$'-/-/-/-/-//--//-//-//-
÷\#_÷$÷$#$÷$÷$#$÷$÷$!$!$#_'_#=$"&÷$÷€#$#$
÷€#$'€÷€÷:$!$÷€#_#€#€?*_!#????·°·°<ΜΜ·§]¿¤>¿·Μ<`<°<Μ
§{Μ<¿>°{|>¥·￦<Μ°·¥<Μ]©·°·Μ·|·§°₪Μ₪©₪Μ₪Μ₪₪Μ©₪©₪©©₪|₪₹₹₪¤₹₪₹₪₹₪₹₹₪₹₪₹៛₪₹Μ៛§{Μ<¬
§·§·§·§{|₪|₪|₹₪₹₪₹₪₹ռօռօռօռօֆօգըօըռճեօճռ
եօօռռօռօեօդօռռօռօိသ်သ်သ်
ိူ်ူ်ူ််သ292်ူန92်သ်သနသနသ3သ်နစနသ်သနစနသ်န939န9392992922
ဖ့ြြြြြြြူ်သါးမါုခ်ူါုု်သ်ိူ်ု်
ိူိူိူဖူိူိူခး်ူိိူ်ုထ်ူိူိူ်ု်သနါူ်ု့ဘည်ိညိာထ.ိူထ,ိ်ိူ်ုိိုိ
ူျူိူ်သ်သ်ူ်ူ်ထူ်ူ်ူိူိူိူိူ်ူ်ူိူိူိုိုိုိိူိုိသိထုနစဖူဖ
!%_$!%$!%_-$%!$!%!
!/_/#(-/$!$-/$-/-/
-_;!_!;__-/_/-_/--$#$#$'-/-/-/-/-//--//-//-//-
÷\#_÷$÷$#$÷$÷$#$÷$÷$!$!$#_'_#=$"&÷$÷€#$#$
÷€#$'€÷€÷:$!$÷€#_#€#€?*_!#????·°·°<ΜΜ·§]¿¤>¿·Μ<`<°<Μ
§{Μ<¿>°{|>¥·￦<Μ°·¥<Μ]©·°·Μ·|·§°₪Μ₪©₪Μ₪Μ₪₪Μ©₪©₪©©₪|₪₹₹₪¤₹₪₹₪₹₪₹₹₪₹₪₹៛₪₹Μ៛§{Μ<¬
§·§·§·§{|₪|₪|₹₪₹₪₹₪₹ռօռօռօռօֆօգըօըռճեօճռ
եօօռռօռօեօդօռռօռօိသ်သ်သ်
ိူ်ူ်ူ််သ292်ူန92်သ်သနသနသ3သ်နစနသ်သနစနသ်န939န9392992922
ဖ့ြြြြြြြူ်သါးမါုခ်ူါုု်သ်ိူ်ု်
ိူိူိူဖူိူိူခး်ူိိူ်ုထ်ူိူိူ်ု်သနါူ်ု့ဘည်ိညိာထ.ိူထ,ိ်ိူ်ုိိုိ
ူျူိူ်သ်သ်ူ်ူ်ထူ်ူ်ူိူိူိူိူ်ူ်ူိူိူိုိုိုိိူိုိသိထုနစဖူဖ
]
}
mov bp*
mov arm64
mov x86_64
mov riscv
BBN??""";
BMM??""";
set view vel*='120fps'
set view vel!*='1-2-0-f-p-s'
set ui_vvv*='0xFFFG'
